package com.sinosoft.efiling.hibernate.entity;

// Generated 2013-4-25 20:00:25 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import com.sinosoft.util.hibernate.entity.EntityOperatorSupport;

/**
 * FileLendingReturn generated by hbm2java
 */
public class FileLendingReturn extends EntityOperatorSupport<String> {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5017483229110579495L;
	private Company borrowerDept;
	private Company borrowerCompany;
	private User borrower;
	private String borrowerName;  //归还人名称
	private String borrowerDeptName; //归还人所属部门名称
	private String borrowerCompanyName;//归还人所属分公司名称
	private Set<FileLendingDetail> fileLendingDetails = new HashSet<FileLendingDetail>(0);
	private Set<FileLending> fileLendings = new HashSet<FileLending>(0);

	public String getBorrowerName() {
		return borrowerName;
	}

	public void setBorrowerName(String borrowerName) {
		this.borrowerName = borrowerName;
	}

	public String getBorrowerDeptName() {
		return borrowerDeptName;
	}

	public void setBorrowerDeptName(String borrowerDeptName) {
		this.borrowerDeptName = borrowerDeptName;
	}

	public String getBorrowerCompanyName() {
		return borrowerCompanyName;
	}

	public void setBorrowerCompanyName(String borrowerCompanyName) {
		this.borrowerCompanyName = borrowerCompanyName;
	}
	public FileLendingReturn() {
	}

	public Company getBorrowerDept() {
		return borrowerDept;
	}

	public void setBorrowerDept(Company borrowerDept) {
		this.borrowerDept = borrowerDept;
	}

	public Company getBorrowerCompany() {
		return borrowerCompany;
	}

	public void setBorrowerCompany(Company borrowerCompany) {
		this.borrowerCompany = borrowerCompany;
	}

	public User getBorrower() {
		return borrower;
	}

	public void setBorrower(User borrower) {
		this.borrower = borrower;
	}

	public Set<FileLendingDetail> getFileLendingDetails() {
		return fileLendingDetails;
	}

	public void setFileLendingDetails(Set<FileLendingDetail> fileLendingDetails) {
		this.fileLendingDetails = fileLendingDetails;
	}

	public Set<FileLending> getFileLendings() {
		return fileLendings;
	}

	public void setFileLendings(Set<FileLending> fileLendings) {
		this.fileLendings = fileLendings;
	}

}
