package com.sinosoft.efiling.hibernate.entity;

// Generated 2013-7-1 18:57:58 by Hibernate Tools 4.0.0

import java.io.Serializable;

/**
 * PrpCInsuredId generated by hbm2java
 */
@SuppressWarnings("serial")
public class PrpCInsuredId implements Serializable {

	private String policyno;
	private double serialno;

	public PrpCInsuredId() {
	}

	public PrpCInsuredId(String policyno, double serialno) {
		this.policyno = policyno;
		this.serialno = serialno;
	}

	public String getPolicyno() {
		return this.policyno;
	}

	public void setPolicyno(String policyno) {
		this.policyno = policyno;
	}

	public double getSerialno() {
		return this.serialno;
	}

	public void setSerialno(double serialno) {
		this.serialno = serialno;
	}

	public boolean equals(Object other) {
		if ((this == other)) return true;
		if ((other == null)) return false;
		if (!(other instanceof PrpCInsuredId)) return false;
		PrpCInsuredId castOther = (PrpCInsuredId) other;

		return ((this.getPolicyno() == castOther.getPolicyno()) || (this.getPolicyno() != null
				&& castOther.getPolicyno() != null && this.getPolicyno().equals(castOther.getPolicyno())))
				&& (this.getSerialno() == castOther.getSerialno());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getPolicyno() == null ? 0 : this.getPolicyno().hashCode());
		result = 37 * result + (int) this.getSerialno();
		return result;
	}

}
