package com.sinosoft.efiling.hibernate.entity;

// Generated 2013-7-9 18:46:45 by Hibernate Tools 4.0.0

import java.io.Serializable;


/**
 * PrpCItemcarId generated by hbm2java
 */
@SuppressWarnings("serial")
public class PrpCItemcarId implements Serializable {

	private String policyno;
	private Double itemno;

	public PrpCItemcarId() {
	}

	public PrpCItemcarId(String policyno, Double itemno) {
		this.policyno = policyno;
		this.itemno = itemno;
	}

	public String getPolicyno() {
		return this.policyno;
	}

	public void setPolicyno(String policyno) {
		this.policyno = policyno;
	}

	public double getItemno() {
		return this.itemno;
	}

	public void setItemno(double itemno) {
		this.itemno = itemno;
	}

	 

}
