package com.sinosoft.efiling.hibernate.entity;

import java.io.Serializable;

// Generated 2013-7-4 12:09:26 by Hibernate Tools 4.0.0


/**
 * PrpCMainsubId generated by hbm2java
 */
@SuppressWarnings("serial")
public class PrpCMainsubId implements Serializable {

	private String policyno;
	private String mainpolicyno;
	public PrpCMainsubId() {
	}

	public PrpCMainsubId(String policyno, String mainpolicyno) {
		this.policyno = policyno;
		this.mainpolicyno = mainpolicyno;
	}
	 
	public String getPolicyno() {
		return this.policyno;
	}

	public void setPolicyno(String policyno) {
		this.policyno = policyno;
	}

	public String getMainpolicyno() {
		return this.mainpolicyno;
	}

	public void setMainpolicyno(String mainpolicyno) {
		this.mainpolicyno = mainpolicyno;
	}

}
