package com.sinosoft.efiling.hibernate.entity;

import com.sinosoft.util.hibernate.entity.EntitySupport;

// Generated 2013-7-1 18:57:58 by Hibernate Tools 4.0.0

/**
 * PrpDUwmtypes generated by hbm2java
 */
@SuppressWarnings("serial")
public class PrpDUwmtypes extends EntitySupport<PrpDUwmtypesId> {

	// private PrpDUwmtypesId id;
	private String typEName;
	private String sort;
	private String attribute1;
	private String attribute2;
	private String attribute3;

	public PrpDUwmtypes() {
	}

	public PrpDUwmtypes(PrpDUwmtypesId id) {
		this.id = id;
	}

	public PrpDUwmtypes(PrpDUwmtypesId id, String typEName, String sort, String attribute1, String attribute2,
			String attribute3) {
		this.id = id;
		this.typEName = typEName;
		this.sort = sort;
		this.attribute1 = attribute1;
		this.attribute2 = attribute2;
		this.attribute3 = attribute3;
	}

	// public PrpDUwmtypesId getId() {
	// return this.id;
	// }
	//
	// public void setId(PrpDUwmtypesId id) {
	// this.id = id;
	// }

	public String getTypEName() {
		return this.typEName;
	}

	public void setTypEName(String typEName) {
		this.typEName = typEName;
	}

	public String getSort() {
		return this.sort;
	}

	public void setSort(String sort) {
		this.sort = sort;
	}

	public String getAttribute1() {
		return this.attribute1;
	}

	public void setAttribute1(String attribute1) {
		this.attribute1 = attribute1;
	}

	public String getAttribute2() {
		return this.attribute2;
	}

	public void setAttribute2(String attribute2) {
		this.attribute2 = attribute2;
	}

	public String getAttribute3() {
		return this.attribute3;
	}

	public void setAttribute3(String attribute3) {
		this.attribute3 = attribute3;
	}

}
