package com.sinosoft.efiling.hibernate.entity;

import com.sinosoft.util.hibernate.entity.EntitySupport;

// Generated 2013-7-4 12:09:26 by Hibernate Tools 4.0.0

/**
 * PrpPMainsub generated by hbm2java
 */
@SuppressWarnings("serial")
public class PrpPMainsub extends EntitySupport<PrpPMainsubId> {

	private PrpPMainsubId id;
	private String flag;
	private String remark;
	private String transStatus;
	private Double enforcepremium;
	private Double enforcecarshiptax;
	private String transType;
	private Double chgenforcepremium;
	private String combineFlag;
	private String mainproposalno;
	private Double chgenforcecarshiptax;
	public PrpPMainsubId getId() {
		return id;
	}
	public void setId(PrpPMainsubId id) {
		this.id = id;
	}
	public String getFlag() {
		return flag;
	}
	public void setFlag(String flag) {
		this.flag = flag;
	}
	public String getRemark() {
		return remark;
	}
	public void setRemark(String remark) {
		this.remark = remark;
	}
	public String getTransStatus() {
		return transStatus;
	}
	public void setTransStatus(String transStatus) {
		this.transStatus = transStatus;
	}
	public Double getEnforcepremium() {
		return enforcepremium;
	}
	public void setEnforcepremium(Double enforcepremium) {
		this.enforcepremium = enforcepremium;
	}
	public Double getEnforcecarshiptax() {
		return enforcecarshiptax;
	}
	public void setEnforcecarshiptax(Double enforcecarshiptax) {
		this.enforcecarshiptax = enforcecarshiptax;
	}
	public String getTransType() {
		return transType;
	}
	public void setTransType(String transType) {
		this.transType = transType;
	}
	public Double getChgenforcepremium() {
		return chgenforcepremium;
	}
	public void setChgenforcepremium(Double chgenforcepremium) {
		this.chgenforcepremium = chgenforcepremium;
	}
	public String getCombineFlag() {
		return combineFlag;
	}
	public void setCombineFlag(String combineFlag) {
		this.combineFlag = combineFlag;
	}
	public String getMainproposalno() {
		return mainproposalno;
	}
	public void setMainproposalno(String mainproposalno) {
		this.mainproposalno = mainproposalno;
	}
	public Double getChgenforcecarshiptax() {
		return chgenforcecarshiptax;
	}
	public void setChgenforcecarshiptax(Double chgenforcecarshiptax) {
		this.chgenforcecarshiptax = chgenforcecarshiptax;
	}

	 
}
