package com.sinosoft.efiling.hibernate.entity;

// Generated 2013-7-1 18:57:58 by Hibernate Tools 4.0.0

import java.io.Serializable;


/**
 * PrpTInsuredId generated by hbm2java
 */
@SuppressWarnings("serial")
public class PrpTInsuredId implements Serializable {

	private String proposalno;
	private double serialno;

	public PrpTInsuredId() {
	}

	public PrpTInsuredId(String proposalno, double serialno) {
		this.proposalno = proposalno;
		this.serialno = serialno;
	}

	public String getProposalno() {
		return this.proposalno;
	}

	public void setProposalno(String proposalno) {
		this.proposalno = proposalno;
	}

	public double getSerialno() {
		return this.serialno;
	}

	public void setSerialno(double serialno) {
		this.serialno = serialno;
	}

	public boolean equals(Object other) {
		if ((this == other)) return true;
		if ((other == null)) return false;
		if (!(other instanceof PrpTInsuredId)) return false;
		PrpTInsuredId castOther = (PrpTInsuredId) other;

		return ((this.getProposalno() == castOther.getProposalno()) || (this.getProposalno() != null
				&& castOther.getProposalno() != null && this.getProposalno().equals(castOther.getProposalno())))
				&& (this.getSerialno() == castOther.getSerialno());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getProposalno() == null ? 0 : this.getProposalno().hashCode());
		result = 37 * result + (int) this.getSerialno();
		return result;
	}

}
