package com.sinosoft.efiling.hibernate.entity;

// Generated 2013-7-4 12:09:26 by Hibernate Tools 4.0.0

import java.io.Serializable;

/**
 * PrpTMainsubId generated by hbm2java
 */
@SuppressWarnings("serial")
public class PrpTMainsubId implements Serializable {

	private String proposalno;
	private String mainpolicyno;

	public PrpTMainsubId() {
	}

	public PrpTMainsubId(String proposalno, String mainpolicyno) {
		this.proposalno = proposalno;
		this.mainpolicyno = mainpolicyno;
	}

	public String getProposalno() {
		return this.proposalno;
	}

	public void setProposalno(String proposalno) {
		this.proposalno = proposalno;
	}

	public String getMainpolicyno() {
		return this.mainpolicyno;
	}

	public void setMainpolicyno(String mainpolicyno) {
		this.mainpolicyno = mainpolicyno;
	}

	public boolean equals(Object other) {
		if ((this == other)) return true;
		if ((other == null)) return false;
		if (!(other instanceof PrpTMainsubId)) return false;
		PrpTMainsubId castOther = (PrpTMainsubId) other;

		return ((this.getProposalno() == castOther.getProposalno()) || (this.getProposalno() != null
				&& castOther.getProposalno() != null && this.getProposalno().equals(castOther.getProposalno())))
				&& ((this.getMainpolicyno() == castOther.getMainpolicyno()) || (this.getMainpolicyno() != null
						&& castOther.getMainpolicyno() != null && this.getMainpolicyno().equals(
						castOther.getMainpolicyno())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getProposalno() == null ? 0 : this.getProposalno().hashCode());
		result = 37 * result + (getMainpolicyno() == null ? 0 : this.getMainpolicyno().hashCode());
		return result;
	}

}
