package com.sinosoft.efiling.hibernate.entity;

import com.sinosoft.util.hibernate.entity.EntitySupport;

// Generated 2013-7-1 18:57:58 by Hibernate Tools 4.0.0


/**
 * PrpDCoderisk generated by hbm2java
 */
@SuppressWarnings("serial")
public class PrpDCoderisk extends EntitySupport<PrpDCoderiskId> {

	private PrpDCoderiskId id;

	public PrpDCoderisk() {
	}

	public PrpDCoderisk(PrpDCoderiskId id) {
		this.id = id;
	}

	public PrpDCoderiskId getId() {
		return this.id;
	}

	public void setId(PrpDCoderiskId id) {
		this.id = id;
	}

}
