package com.sinosoft.efiling.hibernate.entity;

// Generated 2013-7-1 18:57:58 by Hibernate Tools 4.0.0

import java.util.Date;

import com.sinosoft.util.hibernate.entity.EntitySupport;


/**
 * PrpPMain generated by hbm2java
 */
@SuppressWarnings("serial")
public class PrpPMain extends EntitySupport<String> {

	private String id;//endorseno;
	private String policyno;
	private String classCode;
	private String riskCode;
	private String proposalno;
	private String contractno;
	private String policysort;
	private String printno;
	private String businessnature;
	private String language;
	private String policyType;
	private String appliCode;
	private String appliName;
	private String appliAddress;
	private String insuredCode;
	private String insuredName;
	private String insuredAddress;
	private Date operateDate;
	private Date startDate;
	private Double starthour;
	private Date endDate;
	private Double endhour;
	private Double purerate;
	private Double disrate;
	private Double discount;
	private String currency;
	private Double sumValue;
	private Double sumamount;
	private Double sumdiscount;
	private Double sumpremium;
	private Double sumsubprem;
	private Double sumquantity;
	private String judicalCode;
	private String judicalscope;
	private String autotransrenewFlag;
	private String arguesolution;
	private String arbitboardName;
	private Double paytimes;
	private Double endorsetimes;
	private Double claimtimes;
	private String makeCom;
	private String operatesite;
	private String comCode;
	private String handlerCode;
	private String handler1Code;
	private String approverCode;
	private String underwriteCode;
	private String underwritEName;
	private String operatorCode;
	private Date inputDate;
	private Double inputhour;
	private Date underwriteendDate;
	private Date statisticsym;
	private String agentCode;
	private String coinsFlag;
	private String reinsFlag;
	private String allinsFlag;
	private String underwriteFlag;
	private String othFlag;
	private String flag;
	private Double chgamount;
	private Double chgpremium;
	private Double chgsubprem;
	private Double chgquantity;
	private Double disrate1;
	private String businessFlag;
	private String updaterCode;
	private Date updateDate;
	private String updatehour;
	private Date signDate;
	private String shareholderFlag;
	private String agreementNo;
	private String inquiryno;
	private String paymode;
	private String remark;
	private String visaCode;
	private String manualType;
	private Double startminute;
	private Double endminute;
	private String nationFlag;
	private String papolicyno;
	private String businessType;
	private String businessType1;
	private String originpolicyno;
	private String conveyFlag;
	private String riskmark;
	private String uwapprovalno;
	private String custconnFlag;
	private Double prepaidrate;
	private Double sumestimatedpremium;
	private Double lowestpremium;
	private Double sumestimatedamount;
	private String openpolicyFlag;
	private String currency1;
	private String groupbusinessFlag;
	private String groupbusinessCode;
	private String tradingautosFlag;
	private String affinityCode;
	private String surveyFlag;
	private String agentName;
	private String agreementName;
	private String affinityName;
	private String anonymityFlag;
	private Double planexchangerate;
	private String riskversion;
	private String comSign;
	private String discountlimit;
	private String addinputFlag;
	private String policynatureFlag;
	private String clientType;
	private String handlerName;
	private Double agentlosration;
	private String enforceonly;
	private String salerNumber;
	private String salerName;
	private Date firstendorseDate;
	private Date firstuwendorseDate;
	private String polisource;
	private String totalloss;
	private Date firstrecordDate;
	private Date firstunderwriteDate;
	private String deliverymode;
	private String ecardType;
	private String websource;
	private String settleFlag;
	private String carTypeCode;
	private String carinsuranceType;
	//private String specialRisk;
	private Date accountreturnDate;

	public PrpPMain() {
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getPolicyno() {
		return policyno;
	}

	public void setPolicyno(String policyno) {
		this.policyno = policyno;
	}

	public String getClassCode() {
		return classCode;
	}

	public void setClassCode(String classCode) {
		this.classCode = classCode;
	}

	public String getRiskCode() {
		return riskCode;
	}

	public void setRiskCode(String riskCode) {
		this.riskCode = riskCode;
	}

	public String getProposalno() {
		return proposalno;
	}

	public void setProposalno(String proposalno) {
		this.proposalno = proposalno;
	}

	public String getContractno() {
		return contractno;
	}

	public void setContractno(String contractno) {
		this.contractno = contractno;
	}

	public String getPolicysort() {
		return policysort;
	}

	public void setPolicysort(String policysort) {
		this.policysort = policysort;
	}

	public String getPrintno() {
		return printno;
	}

	public void setPrintno(String printno) {
		this.printno = printno;
	}

	public String getBusinessnature() {
		return businessnature;
	}

	public void setBusinessnature(String businessnature) {
		this.businessnature = businessnature;
	}

	public String getLanguage() {
		return language;
	}

	public void setLanguage(String language) {
		this.language = language;
	}

	public String getPolicyType() {
		return policyType;
	}

	public void setPolicyType(String policyType) {
		this.policyType = policyType;
	}

	public String getAppliCode() {
		return appliCode;
	}

	public void setAppliCode(String appliCode) {
		this.appliCode = appliCode;
	}

	public String getAppliName() {
		return appliName;
	}

	public void setAppliName(String appliName) {
		this.appliName = appliName;
	}

	public String getAppliAddress() {
		return appliAddress;
	}

	public void setAppliAddress(String appliAddress) {
		this.appliAddress = appliAddress;
	}

	public String getInsuredCode() {
		return insuredCode;
	}

	public void setInsuredCode(String insuredCode) {
		this.insuredCode = insuredCode;
	}

	public String getInsuredName() {
		return insuredName;
	}

	public void setInsuredName(String insuredName) {
		this.insuredName = insuredName;
	}

	public String getInsuredAddress() {
		return insuredAddress;
	}

	public void setInsuredAddress(String insuredAddress) {
		this.insuredAddress = insuredAddress;
	}

	public Date getOperateDate() {
		return operateDate;
	}

	public void setOperateDate(Date operateDate) {
		this.operateDate = operateDate;
	}

	public Date getStartDate() {
		return startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Double getStarthour() {
		return starthour;
	}

	public void setStarthour(Double starthour) {
		this.starthour = starthour;
	}

	public Date getEndDate() {
		return endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public Double getEndhour() {
		return endhour;
	}

	public void setEndhour(Double endhour) {
		this.endhour = endhour;
	}

	public Double getPurerate() {
		return purerate;
	}

	public void setPurerate(Double purerate) {
		this.purerate = purerate;
	}

	public Double getDisrate() {
		return disrate;
	}

	public void setDisrate(Double disrate) {
		this.disrate = disrate;
	}

	public Double getDiscount() {
		return discount;
	}

	public void setDiscount(Double discount) {
		this.discount = discount;
	}

	public String getCurrency() {
		return currency;
	}

	public void setCurrency(String currency) {
		this.currency = currency;
	}

	public Double getSumValue() {
		return sumValue;
	}

	public void setSumValue(Double sumValue) {
		this.sumValue = sumValue;
	}

	public Double getSumamount() {
		return sumamount;
	}

	public void setSumamount(Double sumamount) {
		this.sumamount = sumamount;
	}

	public Double getSumdiscount() {
		return sumdiscount;
	}

	public void setSumdiscount(Double sumdiscount) {
		this.sumdiscount = sumdiscount;
	}

	public Double getSumpremium() {
		return sumpremium;
	}

	public void setSumpremium(Double sumpremium) {
		this.sumpremium = sumpremium;
	}

	public Double getSumsubprem() {
		return sumsubprem;
	}

	public void setSumsubprem(Double sumsubprem) {
		this.sumsubprem = sumsubprem;
	}

	public Double getSumquantity() {
		return sumquantity;
	}

	public void setSumquantity(Double sumquantity) {
		this.sumquantity = sumquantity;
	}

	public String getJudicalCode() {
		return judicalCode;
	}

	public void setJudicalCode(String judicalCode) {
		this.judicalCode = judicalCode;
	}

	public String getJudicalscope() {
		return judicalscope;
	}

	public void setJudicalscope(String judicalscope) {
		this.judicalscope = judicalscope;
	}

	public String getAutotransrenewFlag() {
		return autotransrenewFlag;
	}

	public void setAutotransrenewFlag(String autotransrenewFlag) {
		this.autotransrenewFlag = autotransrenewFlag;
	}

	public String getArguesolution() {
		return arguesolution;
	}

	public void setArguesolution(String arguesolution) {
		this.arguesolution = arguesolution;
	}

	public String getArbitboardName() {
		return arbitboardName;
	}

	public void setArbitboardName(String arbitboardName) {
		this.arbitboardName = arbitboardName;
	}

	public Double getPaytimes() {
		return paytimes;
	}

	public void setPaytimes(Double paytimes) {
		this.paytimes = paytimes;
	}

	public Double getEndorsetimes() {
		return endorsetimes;
	}

	public void setEndorsetimes(Double endorsetimes) {
		this.endorsetimes = endorsetimes;
	}

	public Double getClaimtimes() {
		return claimtimes;
	}

	public void setClaimtimes(Double claimtimes) {
		this.claimtimes = claimtimes;
	}

	public String getMakeCom() {
		return makeCom;
	}

	public void setMakeCom(String makeCom) {
		this.makeCom = makeCom;
	}

	public String getOperatesite() {
		return operatesite;
	}

	public void setOperatesite(String operatesite) {
		this.operatesite = operatesite;
	}

	public String getComCode() {
		return comCode;
	}

	public void setComCode(String comCode) {
		this.comCode = comCode;
	}

	public String getHandlerCode() {
		return handlerCode;
	}

	public void setHandlerCode(String handlerCode) {
		this.handlerCode = handlerCode;
	}

	public String getHandler1Code() {
		return handler1Code;
	}

	public void setHandler1Code(String handler1Code) {
		this.handler1Code = handler1Code;
	}

	public String getApproverCode() {
		return approverCode;
	}

	public void setApproverCode(String approverCode) {
		this.approverCode = approverCode;
	}

	public String getUnderwriteCode() {
		return underwriteCode;
	}

	public void setUnderwriteCode(String underwriteCode) {
		this.underwriteCode = underwriteCode;
	}

	public String getUnderwritEName() {
		return underwritEName;
	}

	public void setUnderwritEName(String underwritEName) {
		this.underwritEName = underwritEName;
	}

	public String getOperatorCode() {
		return operatorCode;
	}

	public void setOperatorCode(String operatorCode) {
		this.operatorCode = operatorCode;
	}

	public Date getInputDate() {
		return inputDate;
	}

	public void setInputDate(Date inputDate) {
		this.inputDate = inputDate;
	}

	public Double getInputhour() {
		return inputhour;
	}

	public void setInputhour(Double inputhour) {
		this.inputhour = inputhour;
	}

	public Date getUnderwriteendDate() {
		return underwriteendDate;
	}

	public void setUnderwriteendDate(Date underwriteendDate) {
		this.underwriteendDate = underwriteendDate;
	}

	public Date getStatisticsym() {
		return statisticsym;
	}

	public void setStatisticsym(Date statisticsym) {
		this.statisticsym = statisticsym;
	}

	public String getAgentCode() {
		return agentCode;
	}

	public void setAgentCode(String agentCode) {
		this.agentCode = agentCode;
	}

	public String getCoinsFlag() {
		return coinsFlag;
	}

	public void setCoinsFlag(String coinsFlag) {
		this.coinsFlag = coinsFlag;
	}

	public String getReinsFlag() {
		return reinsFlag;
	}

	public void setReinsFlag(String reinsFlag) {
		this.reinsFlag = reinsFlag;
	}

	public String getAllinsFlag() {
		return allinsFlag;
	}

	public void setAllinsFlag(String allinsFlag) {
		this.allinsFlag = allinsFlag;
	}

	public String getUnderwriteFlag() {
		return underwriteFlag;
	}

	public void setUnderwriteFlag(String underwriteFlag) {
		this.underwriteFlag = underwriteFlag;
	}

	public String getOthFlag() {
		return othFlag;
	}

	public void setOthFlag(String othFlag) {
		this.othFlag = othFlag;
	}

	public String getFlag() {
		return flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	public Double getChgamount() {
		return chgamount;
	}

	public void setChgamount(Double chgamount) {
		this.chgamount = chgamount;
	}

	public Double getChgpremium() {
		return chgpremium;
	}

	public void setChgpremium(Double chgpremium) {
		this.chgpremium = chgpremium;
	}

	public Double getChgsubprem() {
		return chgsubprem;
	}

	public void setChgsubprem(Double chgsubprem) {
		this.chgsubprem = chgsubprem;
	}

	public Double getChgquantity() {
		return chgquantity;
	}

	public void setChgquantity(Double chgquantity) {
		this.chgquantity = chgquantity;
	}

	public Double getDisrate1() {
		return disrate1;
	}

	public void setDisrate1(Double disrate1) {
		this.disrate1 = disrate1;
	}

	public String getBusinessFlag() {
		return businessFlag;
	}

	public void setBusinessFlag(String businessFlag) {
		this.businessFlag = businessFlag;
	}

	public String getUpdaterCode() {
		return updaterCode;
	}

	public void setUpdaterCode(String updaterCode) {
		this.updaterCode = updaterCode;
	}

	public Date getUpdateDate() {
		return updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public String getUpdatehour() {
		return updatehour;
	}

	public void setUpdatehour(String updatehour) {
		this.updatehour = updatehour;
	}

	public Date getSignDate() {
		return signDate;
	}

	public void setSignDate(Date signDate) {
		this.signDate = signDate;
	}

	public String getShareholderFlag() {
		return shareholderFlag;
	}

	public void setShareholderFlag(String shareholderFlag) {
		this.shareholderFlag = shareholderFlag;
	}

	public String getAgreementNo() {
		return agreementNo;
	}

	public void setAgreementNo(String agreementNo) {
		this.agreementNo = agreementNo;
	}

	public String getInquiryno() {
		return inquiryno;
	}

	public void setInquiryno(String inquiryno) {
		this.inquiryno = inquiryno;
	}

	public String getPaymode() {
		return paymode;
	}

	public void setPaymode(String paymode) {
		this.paymode = paymode;
	}

	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getVisaCode() {
		return visaCode;
	}

	public void setVisaCode(String visaCode) {
		this.visaCode = visaCode;
	}

	public String getManualType() {
		return manualType;
	}

	public void setManualType(String manualType) {
		this.manualType = manualType;
	}

	public Double getStartminute() {
		return startminute;
	}

	public void setStartminute(Double startminute) {
		this.startminute = startminute;
	}

	public Double getEndminute() {
		return endminute;
	}

	public void setEndminute(Double endminute) {
		this.endminute = endminute;
	}

	public String getNationFlag() {
		return nationFlag;
	}

	public void setNationFlag(String nationFlag) {
		this.nationFlag = nationFlag;
	}

	public String getPapolicyno() {
		return papolicyno;
	}

	public void setPapolicyno(String papolicyno) {
		this.papolicyno = papolicyno;
	}

	public String getBusinessType() {
		return businessType;
	}

	public void setBusinessType(String businessType) {
		this.businessType = businessType;
	}

	public String getBusinessType1() {
		return businessType1;
	}

	public void setBusinessType1(String businessType1) {
		this.businessType1 = businessType1;
	}

	public String getOriginpolicyno() {
		return originpolicyno;
	}

	public void setOriginpolicyno(String originpolicyno) {
		this.originpolicyno = originpolicyno;
	}

	public String getConveyFlag() {
		return conveyFlag;
	}

	public void setConveyFlag(String conveyFlag) {
		this.conveyFlag = conveyFlag;
	}

	public String getRiskmark() {
		return riskmark;
	}

	public void setRiskmark(String riskmark) {
		this.riskmark = riskmark;
	}

	public String getUwapprovalno() {
		return uwapprovalno;
	}

	public void setUwapprovalno(String uwapprovalno) {
		this.uwapprovalno = uwapprovalno;
	}

	public String getCustconnFlag() {
		return custconnFlag;
	}

	public void setCustconnFlag(String custconnFlag) {
		this.custconnFlag = custconnFlag;
	}

	public Double getPrepaidrate() {
		return prepaidrate;
	}

	public void setPrepaidrate(Double prepaidrate) {
		this.prepaidrate = prepaidrate;
	}

	public Double getSumestimatedpremium() {
		return sumestimatedpremium;
	}

	public void setSumestimatedpremium(Double sumestimatedpremium) {
		this.sumestimatedpremium = sumestimatedpremium;
	}

	public Double getLowestpremium() {
		return lowestpremium;
	}

	public void setLowestpremium(Double lowestpremium) {
		this.lowestpremium = lowestpremium;
	}

	public Double getSumestimatedamount() {
		return sumestimatedamount;
	}

	public void setSumestimatedamount(Double sumestimatedamount) {
		this.sumestimatedamount = sumestimatedamount;
	}

	public String getOpenpolicyFlag() {
		return openpolicyFlag;
	}

	public void setOpenpolicyFlag(String openpolicyFlag) {
		this.openpolicyFlag = openpolicyFlag;
	}

	public String getCurrency1() {
		return currency1;
	}

	public void setCurrency1(String currency1) {
		this.currency1 = currency1;
	}

	public String getGroupbusinessFlag() {
		return groupbusinessFlag;
	}

	public void setGroupbusinessFlag(String groupbusinessFlag) {
		this.groupbusinessFlag = groupbusinessFlag;
	}

	public String getGroupbusinessCode() {
		return groupbusinessCode;
	}

	public void setGroupbusinessCode(String groupbusinessCode) {
		this.groupbusinessCode = groupbusinessCode;
	}

	public String getTradingautosFlag() {
		return tradingautosFlag;
	}

	public void setTradingautosFlag(String tradingautosFlag) {
		this.tradingautosFlag = tradingautosFlag;
	}

	public String getAffinityCode() {
		return affinityCode;
	}

	public void setAffinityCode(String affinityCode) {
		this.affinityCode = affinityCode;
	}

	public String getSurveyFlag() {
		return surveyFlag;
	}

	public void setSurveyFlag(String surveyFlag) {
		this.surveyFlag = surveyFlag;
	}

	public String getAgentName() {
		return agentName;
	}

	public void setAgentName(String agentName) {
		this.agentName = agentName;
	}

	public String getAgreementName() {
		return agreementName;
	}

	public void setAgreementName(String agreementName) {
		this.agreementName = agreementName;
	}

	public String getAffinityName() {
		return affinityName;
	}

	public void setAffinityName(String affinityName) {
		this.affinityName = affinityName;
	}

	public String getAnonymityFlag() {
		return anonymityFlag;
	}

	public void setAnonymityFlag(String anonymityFlag) {
		this.anonymityFlag = anonymityFlag;
	}

	public Double getPlanexchangerate() {
		return planexchangerate;
	}

	public void setPlanexchangerate(Double planexchangerate) {
		this.planexchangerate = planexchangerate;
	}

	public String getRiskversion() {
		return riskversion;
	}

	public void setRiskversion(String riskversion) {
		this.riskversion = riskversion;
	}

	public String getComSign() {
		return comSign;
	}

	public void setComSign(String comSign) {
		this.comSign = comSign;
	}

	public String getDiscountlimit() {
		return discountlimit;
	}

	public void setDiscountlimit(String discountlimit) {
		this.discountlimit = discountlimit;
	}

	public String getAddinputFlag() {
		return addinputFlag;
	}

	public void setAddinputFlag(String addinputFlag) {
		this.addinputFlag = addinputFlag;
	}

	public String getPolicynatureFlag() {
		return policynatureFlag;
	}

	public void setPolicynatureFlag(String policynatureFlag) {
		this.policynatureFlag = policynatureFlag;
	}

	public String getClientType() {
		return clientType;
	}

	public void setClientType(String clientType) {
		this.clientType = clientType;
	}

	public String getHandlerName() {
		return handlerName;
	}

	public void setHandlerName(String handlerName) {
		this.handlerName = handlerName;
	}

	public Double getAgentlosration() {
		return agentlosration;
	}

	public void setAgentlosration(Double agentlosration) {
		this.agentlosration = agentlosration;
	}

	public String getEnforceonly() {
		return enforceonly;
	}

	public void setEnforceonly(String enforceonly) {
		this.enforceonly = enforceonly;
	}

	public String getSalerNumber() {
		return salerNumber;
	}

	public void setSalerNumber(String salerNumber) {
		this.salerNumber = salerNumber;
	}

	public String getSalerName() {
		return salerName;
	}

	public void setSalerName(String salerName) {
		this.salerName = salerName;
	}

	public Date getFirstendorseDate() {
		return firstendorseDate;
	}

	public void setFirstendorseDate(Date firstendorseDate) {
		this.firstendorseDate = firstendorseDate;
	}

	public Date getFirstuwendorseDate() {
		return firstuwendorseDate;
	}

	public void setFirstuwendorseDate(Date firstuwendorseDate) {
		this.firstuwendorseDate = firstuwendorseDate;
	}

	public String getPolisource() {
		return polisource;
	}

	public void setPolisource(String polisource) {
		this.polisource = polisource;
	}

	public String getTotalloss() {
		return totalloss;
	}

	public void setTotalloss(String totalloss) {
		this.totalloss = totalloss;
	}

	public Date getFirstrecordDate() {
		return firstrecordDate;
	}

	public void setFirstrecordDate(Date firstrecordDate) {
		this.firstrecordDate = firstrecordDate;
	}

	public Date getFirstunderwriteDate() {
		return firstunderwriteDate;
	}

	public void setFirstunderwriteDate(Date firstunderwriteDate) {
		this.firstunderwriteDate = firstunderwriteDate;
	}

	public String getDeliverymode() {
		return deliverymode;
	}

	public void setDeliverymode(String deliverymode) {
		this.deliverymode = deliverymode;
	}

	public String getEcardType() {
		return ecardType;
	}

	public void setEcardType(String ecardType) {
		this.ecardType = ecardType;
	}

	public String getWebsource() {
		return websource;
	}

	public void setWebsource(String websource) {
		this.websource = websource;
	}

	public String getSettleFlag() {
		return settleFlag;
	}

	public void setSettleFlag(String settleFlag) {
		this.settleFlag = settleFlag;
	}

	public String getCarTypeCode() {
		return carTypeCode;
	}

	public void setCarTypeCode(String carTypeCode) {
		this.carTypeCode = carTypeCode;
	}

	public String getCarinsuranceType() {
		return carinsuranceType;
	}

	public void setCarinsuranceType(String carinsuranceType) {
		this.carinsuranceType = carinsuranceType;
	}

/*	public String getSpecialRisk() {
		return specialRisk;
	}

	public void setSpecialRisk(String specialRisk) {
		this.specialRisk = specialRisk;
	}
*/
	public Date getAccountreturnDate() {
		return accountreturnDate;
	}

	public void setAccountreturnDate(Date accountreturnDate) {
		this.accountreturnDate = accountreturnDate;
	}
	
	
}
