package com.sinosoft.efiling.hibernate.entity;

import com.sinosoft.util.hibernate.entity.EntityOperatorSupport;

/**
 * FileType generated by hbm2java
 */
public class FileType extends EntityOperatorSupport<String> {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4659486509517942480L;
	private String name;
	/** 承保系统的资料编号 */
	private String code;
	/** 承保对资料的描述 */
	private String alias;
	/** 资料类型：1承保资料对应的档案；0.影像文件 */
	private String fileModel;

	/** 是否需要原件资料的类型 */
	private String signed;

	/** 是否需要共享的资料类型 */
	private String shared;

	public FileType() {
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getAlias() {
		return alias;
	}

	public void setAlias(String alias) {
		this.alias = alias;
	}

	public String getFileModel() {
		return fileModel;
	}

	public void setFileModel(String fileModel) {
		this.fileModel = fileModel;
	}

	public String getSigned() {
		return signed;
	}

	public void setSigned(String signed) {
		this.signed = signed;
	}

	public String getShared() {
		return shared;
	}

	public void setShared(String shared) {
		this.shared = shared;
	}

}
