package com.sinosoft.efiling.hibernate.entity;

import java.io.Serializable;

/**
 * PrpPMainsubId generated by hbm2java
 */
@SuppressWarnings("serial")
public class PrpPMainsubId implements Serializable {

	private String policyno;
	private String endorseno;
	private String mainpolicyno;

	public PrpPMainsubId() {
	}

	public PrpPMainsubId(String policyno, String mainpolicyno, String endorseno) {
		this.policyno = policyno;
		this.mainpolicyno = mainpolicyno;
		this.endorseno = endorseno;
	}
	 
	public String getEndorseno() {
		return endorseno;
	}

	public void setEndorseno(String endorseno) {
		this.endorseno = endorseno;
	}

	public String getPolicyno() {
		return this.policyno;
	}

	public void setPolicyno(String policyno) {
		this.policyno = policyno;
	}

	public String getMainpolicyno() {
		return this.mainpolicyno;
	}

	public void setMainpolicyno(String mainpolicyno) {
		this.mainpolicyno = mainpolicyno;
	}


}
