package com.sinosoft.efiling.hibernate.entity;

import java.io.Serializable;

// Generated 2013-7-9 18:46:45 by Hibernate Tools 4.0.0


/**
 * PrpTItemcarId generated by hbm2java
 */
@SuppressWarnings("serial")
public class PrpTItemcarId implements Serializable {

	private String proposalno;
	private Double itemno;

	public PrpTItemcarId() {
	}

	public PrpTItemcarId(String proposalno, Double itemno) {
		this.proposalno = proposalno;
		this.itemno = itemno;
	}

	public String getProposalno() {
		return this.proposalno;
	}

	public void setProposalno(String proposalno) {
		this.proposalno = proposalno;
	}

	public Double getItemno() {
		return itemno;
	}

	public void setItemno(Double itemno) {
		this.itemno = itemno;
	}

	 
 
}
