package com.sinosoft.efiling.hibernate.entity;

// Generated 2013-7-1 18:57:58 by Hibernate Tools 4.0.0

import java.io.Serializable;


/**
 * PrpDUwmtypesId generated by hbm2java
 */
@SuppressWarnings("serial")
public class PrpDUwmtypesId implements Serializable {

	private String policyno;
	private String type;

	public PrpDUwmtypesId() {
	}

	public PrpDUwmtypesId(String policyno, String type) {
		this.policyno = policyno;
		this.type = type;
	}

	public String getPolicyno() {
		return this.policyno;
	}

	public void setPolicyno(String policyno) {
		this.policyno = policyno;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public boolean equals(Object other) {
		if ((this == other)) return true;
		if ((other == null)) return false;
		if (!(other instanceof PrpDUwmtypesId)) return false;
		PrpDUwmtypesId castOther = (PrpDUwmtypesId) other;

		return ((this.getPolicyno() == castOther.getPolicyno()) || (this.getPolicyno() != null
				&& castOther.getPolicyno() != null && this.getPolicyno().equals(castOther.getPolicyno())))
				&& ((this.getType() == castOther.getType()) || (this.getType() != null && castOther.getType() != null && this
						.getType().equals(castOther.getType())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getPolicyno() == null ? 0 : this.getPolicyno().hashCode());
		result = 37 * result + (getType() == null ? 0 : this.getType().hashCode());
		return result;
	}

}
