package com.sinosoft.efiling.hibernate.entity;

// Generated 2017-9-7 14:03:48 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Prpccarshiptax generated by hbm2java
 */
@Entity
@Table(name = "PRPCCARSHIPTAX", schema = "DEVUSER")
public class Prpccarshiptax implements java.io.Serializable {

	private String policyno;
	private long serialno;
	private String riskcode;
	private String taxtermtypecode;
	private String taxconditioncode;
	private String taxregistrynumber;
	private String taxpayername;
	private String taxpayeridentificationcode;
	private Date declaredate;
	private String declareStatusIa;
	private String calcTaxFlag;
	private String taxamountFlag;
	private BigDecimal annualtaxdue;
	private BigDecimal sumtaxdefault;
	private BigDecimal sumoverdue;
	private BigDecimal sumtax;
	private String deductionduecode;
	private String deductiontype;
	private BigDecimal deductionrate;
	private BigDecimal deduction;
	private String deductiondocumentnumber;
	private String taxdepartmentcode;
	private String taxdepartment;
	private String taxdocumentnumber;
	private String taxlocationcode;
	private Date taxstartdate;
	private Date taxenddate;
	private String taxunittypecode;
	private BigDecimal unitrate;
	private BigDecimal annualtaxamount;
	private BigDecimal taxdue;
	private Date exceeddate;
	private Integer exceeddayscount;
	private BigDecimal overdue;
	private BigDecimal totalamount;
	private String calculatemode;
	private String finalflag;
	private String flag;
	private String proxytaxdone;
	private Date tax1startdate;
	private Date tax1enddate;
	private BigDecimal tax1due;
	private BigDecimal total1amount;

	public Prpccarshiptax() {
	}

	public Prpccarshiptax(String policyno, long serialno, String riskcode) {
		this.policyno = policyno;
		this.serialno = serialno;
		this.riskcode = riskcode;
	}

	public Prpccarshiptax(String policyno, long serialno, String riskcode,
			String taxtermtypecode, String taxconditioncode,
			String taxregistrynumber, String taxpayername,
			String taxpayeridentificationcode, Date declaredate,
			String declareStatusIa, String calcTaxFlag, String taxamountFlag,
			BigDecimal annualtaxdue, BigDecimal sumtaxdefault,
			BigDecimal sumoverdue, BigDecimal sumtax, String deductionduecode,
			String deductiontype, BigDecimal deductionrate,
			BigDecimal deduction, String deductiondocumentnumber,
			String taxdepartmentcode, String taxdepartment,
			String taxdocumentnumber, String taxlocationcode,
			Date taxstartdate, Date taxenddate, String taxunittypecode,
			BigDecimal unitrate, BigDecimal annualtaxamount, BigDecimal taxdue,
			Date exceeddate, Integer exceeddayscount, BigDecimal overdue,
			BigDecimal totalamount, String calculatemode, String finalflag,
			String flag, String proxytaxdone, Date tax1startdate,
			Date tax1enddate, BigDecimal tax1due, BigDecimal total1amount) {
		this.policyno = policyno;
		this.serialno = serialno;
		this.riskcode = riskcode;
		this.taxtermtypecode = taxtermtypecode;
		this.taxconditioncode = taxconditioncode;
		this.taxregistrynumber = taxregistrynumber;
		this.taxpayername = taxpayername;
		this.taxpayeridentificationcode = taxpayeridentificationcode;
		this.declaredate = declaredate;
		this.declareStatusIa = declareStatusIa;
		this.calcTaxFlag = calcTaxFlag;
		this.taxamountFlag = taxamountFlag;
		this.annualtaxdue = annualtaxdue;
		this.sumtaxdefault = sumtaxdefault;
		this.sumoverdue = sumoverdue;
		this.sumtax = sumtax;
		this.deductionduecode = deductionduecode;
		this.deductiontype = deductiontype;
		this.deductionrate = deductionrate;
		this.deduction = deduction;
		this.deductiondocumentnumber = deductiondocumentnumber;
		this.taxdepartmentcode = taxdepartmentcode;
		this.taxdepartment = taxdepartment;
		this.taxdocumentnumber = taxdocumentnumber;
		this.taxlocationcode = taxlocationcode;
		this.taxstartdate = taxstartdate;
		this.taxenddate = taxenddate;
		this.taxunittypecode = taxunittypecode;
		this.unitrate = unitrate;
		this.annualtaxamount = annualtaxamount;
		this.taxdue = taxdue;
		this.exceeddate = exceeddate;
		this.exceeddayscount = exceeddayscount;
		this.overdue = overdue;
		this.totalamount = totalamount;
		this.calculatemode = calculatemode;
		this.finalflag = finalflag;
		this.flag = flag;
		this.proxytaxdone = proxytaxdone;
		this.tax1startdate = tax1startdate;
		this.tax1enddate = tax1enddate;
		this.tax1due = tax1due;
		this.total1amount = total1amount;
	}

	@Id
	@Column(name = "POLICYNO", unique = true, nullable = false, length = 22)
	public String getPolicyno() {
		return this.policyno;
	}

	public void setPolicyno(String policyno) {
		this.policyno = policyno;
	}

	@Column(name = "SERIALNO", nullable = false, precision = 15, scale = 0)
	public long getSerialno() {
		return this.serialno;
	}

	public void setSerialno(long serialno) {
		this.serialno = serialno;
	}

	@Column(name = "RISKCODE", nullable = false, length = 4)
	public String getRiskcode() {
		return this.riskcode;
	}

	public void setRiskcode(String riskcode) {
		this.riskcode = riskcode;
	}

	@Column(name = "TAXTERMTYPECODE", length = 2)
	public String getTaxtermtypecode() {
		return this.taxtermtypecode;
	}

	public void setTaxtermtypecode(String taxtermtypecode) {
		this.taxtermtypecode = taxtermtypecode;
	}

	@Column(name = "TAXCONDITIONCODE", length = 1)
	public String getTaxconditioncode() {
		return this.taxconditioncode;
	}

	public void setTaxconditioncode(String taxconditioncode) {
		this.taxconditioncode = taxconditioncode;
	}

	@Column(name = "TAXREGISTRYNUMBER", length = 22)
	public String getTaxregistrynumber() {
		return this.taxregistrynumber;
	}

	public void setTaxregistrynumber(String taxregistrynumber) {
		this.taxregistrynumber = taxregistrynumber;
	}

	@Column(name = "TAXPAYERNAME", length = 120)
	public String getTaxpayername() {
		return this.taxpayername;
	}

	public void setTaxpayername(String taxpayername) {
		this.taxpayername = taxpayername;
	}

	@Column(name = "TAXPAYERIDENTIFICATIONCODE", length = 22)
	public String getTaxpayeridentificationcode() {
		return this.taxpayeridentificationcode;
	}

	public void setTaxpayeridentificationcode(String taxpayeridentificationcode) {
		this.taxpayeridentificationcode = taxpayeridentificationcode;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DECLAREDATE", length = 7)
	public Date getDeclaredate() {
		return this.declaredate;
	}

	public void setDeclaredate(Date declaredate) {
		this.declaredate = declaredate;
	}

	@Column(name = "DECLARE_STATUS_IA", length = 1)
	public String getDeclareStatusIa() {
		return this.declareStatusIa;
	}

	public void setDeclareStatusIa(String declareStatusIa) {
		this.declareStatusIa = declareStatusIa;
	}

	@Column(name = "CALC_TAX_FLAG", length = 1)
	public String getCalcTaxFlag() {
		return this.calcTaxFlag;
	}

	public void setCalcTaxFlag(String calcTaxFlag) {
		this.calcTaxFlag = calcTaxFlag;
	}

	@Column(name = "TAXAMOUNT_FLAG", length = 1)
	public String getTaxamountFlag() {
		return this.taxamountFlag;
	}

	public void setTaxamountFlag(String taxamountFlag) {
		this.taxamountFlag = taxamountFlag;
	}

	@Column(name = "ANNUALTAXDUE", precision = 14)
	public BigDecimal getAnnualtaxdue() {
		return this.annualtaxdue;
	}

	public void setAnnualtaxdue(BigDecimal annualtaxdue) {
		this.annualtaxdue = annualtaxdue;
	}

	@Column(name = "SUMTAXDEFAULT", precision = 14)
	public BigDecimal getSumtaxdefault() {
		return this.sumtaxdefault;
	}

	public void setSumtaxdefault(BigDecimal sumtaxdefault) {
		this.sumtaxdefault = sumtaxdefault;
	}

	@Column(name = "SUMOVERDUE", precision = 14)
	public BigDecimal getSumoverdue() {
		return this.sumoverdue;
	}

	public void setSumoverdue(BigDecimal sumoverdue) {
		this.sumoverdue = sumoverdue;
	}

	@Column(name = "SUMTAX", precision = 14)
	public BigDecimal getSumtax() {
		return this.sumtax;
	}

	public void setSumtax(BigDecimal sumtax) {
		this.sumtax = sumtax;
	}

	@Column(name = "DEDUCTIONDUECODE", length = 1)
	public String getDeductionduecode() {
		return this.deductionduecode;
	}

	public void setDeductionduecode(String deductionduecode) {
		this.deductionduecode = deductionduecode;
	}

	@Column(name = "DEDUCTIONTYPE", length = 1)
	public String getDeductiontype() {
		return this.deductiontype;
	}

	public void setDeductiontype(String deductiontype) {
		this.deductiontype = deductiontype;
	}

	@Column(name = "DEDUCTIONRATE", precision = 14)
	public BigDecimal getDeductionrate() {
		return this.deductionrate;
	}

	public void setDeductionrate(BigDecimal deductionrate) {
		this.deductionrate = deductionrate;
	}

	@Column(name = "DEDUCTION", precision = 14)
	public BigDecimal getDeduction() {
		return this.deduction;
	}

	public void setDeduction(BigDecimal deduction) {
		this.deduction = deduction;
	}

	@Column(name = "DEDUCTIONDOCUMENTNUMBER", length = 30)
	public String getDeductiondocumentnumber() {
		return this.deductiondocumentnumber;
	}

	public void setDeductiondocumentnumber(String deductiondocumentnumber) {
		this.deductiondocumentnumber = deductiondocumentnumber;
	}

	@Column(name = "TAXDEPARTMENTCODE", length = 11)
	public String getTaxdepartmentcode() {
		return this.taxdepartmentcode;
	}

	public void setTaxdepartmentcode(String taxdepartmentcode) {
		this.taxdepartmentcode = taxdepartmentcode;
	}

	@Column(name = "TAXDEPARTMENT", length = 100)
	public String getTaxdepartment() {
		return this.taxdepartment;
	}

	public void setTaxdepartment(String taxdepartment) {
		this.taxdepartment = taxdepartment;
	}

	@Column(name = "TAXDOCUMENTNUMBER", length = 30)
	public String getTaxdocumentnumber() {
		return this.taxdocumentnumber;
	}

	public void setTaxdocumentnumber(String taxdocumentnumber) {
		this.taxdocumentnumber = taxdocumentnumber;
	}

	@Column(name = "TAXLOCATIONCODE", length = 6)
	public String getTaxlocationcode() {
		return this.taxlocationcode;
	}

	public void setTaxlocationcode(String taxlocationcode) {
		this.taxlocationcode = taxlocationcode;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "TAXSTARTDATE", length = 7)
	public Date getTaxstartdate() {
		return this.taxstartdate;
	}

	public void setTaxstartdate(Date taxstartdate) {
		this.taxstartdate = taxstartdate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "TAXENDDATE", length = 7)
	public Date getTaxenddate() {
		return this.taxenddate;
	}

	public void setTaxenddate(Date taxenddate) {
		this.taxenddate = taxenddate;
	}

	@Column(name = "TAXUNITTYPECODE", length = 1)
	public String getTaxunittypecode() {
		return this.taxunittypecode;
	}

	public void setTaxunittypecode(String taxunittypecode) {
		this.taxunittypecode = taxunittypecode;
	}

	@Column(name = "UNITRATE", precision = 14)
	public BigDecimal getUnitrate() {
		return this.unitrate;
	}

	public void setUnitrate(BigDecimal unitrate) {
		this.unitrate = unitrate;
	}

	@Column(name = "ANNUALTAXAMOUNT", precision = 14)
	public BigDecimal getAnnualtaxamount() {
		return this.annualtaxamount;
	}

	public void setAnnualtaxamount(BigDecimal annualtaxamount) {
		this.annualtaxamount = annualtaxamount;
	}

	@Column(name = "TAXDUE", precision = 14)
	public BigDecimal getTaxdue() {
		return this.taxdue;
	}

	public void setTaxdue(BigDecimal taxdue) {
		this.taxdue = taxdue;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EXCEEDDATE", length = 7)
	public Date getExceeddate() {
		return this.exceeddate;
	}

	public void setExceeddate(Date exceeddate) {
		this.exceeddate = exceeddate;
	}

	@Column(name = "EXCEEDDAYSCOUNT", precision = 5, scale = 0)
	public Integer getExceeddayscount() {
		return this.exceeddayscount;
	}

	public void setExceeddayscount(Integer exceeddayscount) {
		this.exceeddayscount = exceeddayscount;
	}

	@Column(name = "OVERDUE", precision = 14)
	public BigDecimal getOverdue() {
		return this.overdue;
	}

	public void setOverdue(BigDecimal overdue) {
		this.overdue = overdue;
	}

	@Column(name = "TOTALAMOUNT", precision = 14)
	public BigDecimal getTotalamount() {
		return this.totalamount;
	}

	public void setTotalamount(BigDecimal totalamount) {
		this.totalamount = totalamount;
	}

	@Column(name = "CALCULATEMODE", length = 2)
	public String getCalculatemode() {
		return this.calculatemode;
	}

	public void setCalculatemode(String calculatemode) {
		this.calculatemode = calculatemode;
	}

	@Column(name = "FINALFLAG", length = 1)
	public String getFinalflag() {
		return this.finalflag;
	}

	public void setFinalflag(String finalflag) {
		this.finalflag = finalflag;
	}

	@Column(name = "FLAG", length = 10)
	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	@Column(name = "PROXYTAXDONE", length = 4)
	public String getProxytaxdone() {
		return this.proxytaxdone;
	}

	public void setProxytaxdone(String proxytaxdone) {
		this.proxytaxdone = proxytaxdone;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "TAX1STARTDATE", length = 7)
	public Date getTax1startdate() {
		return this.tax1startdate;
	}

	public void setTax1startdate(Date tax1startdate) {
		this.tax1startdate = tax1startdate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "TAX1ENDDATE", length = 7)
	public Date getTax1enddate() {
		return this.tax1enddate;
	}

	public void setTax1enddate(Date tax1enddate) {
		this.tax1enddate = tax1enddate;
	}

	@Column(name = "TAX1DUE", precision = 14)
	public BigDecimal getTax1due() {
		return this.tax1due;
	}

	public void setTax1due(BigDecimal tax1due) {
		this.tax1due = tax1due;
	}

	@Column(name = "TOTAL1AMOUNT", precision = 14)
	public BigDecimal getTotal1amount() {
		return this.total1amount;
	}

	public void setTotal1amount(BigDecimal total1amount) {
		this.total1amount = total1amount;
	}

}
