package com.sinosoft.efiling.hibernate.entity;

import com.sinosoft.util.hibernate.entity.EntitySupport;


/**
 * PrpCMainsub generated by hbm2java
 */
@SuppressWarnings("serial")
public class PrpCMainsub extends EntitySupport<PrpCMainsubId> {

	private PrpCMainsubId id;
	
	private String endorseno;
	private String flag;
	private String remark;
	private Double balancetimes;
	private Double enforcepremium;
	private Double enforcecarshiptax;
	private String transType;
	private String transStatus;
	private String combineFlag;
	private String mainproposalno;
	
	public String getEndorseno() {
		return this.endorseno;
	}

	public void setEndorseno(String endorseno) {
		this.endorseno = endorseno;
	}

	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Double getBalancetimes() {
		return this.balancetimes;
	}

	public void setBalancetimes(Double balancetimes) {
		this.balancetimes = balancetimes;
	}

	public Double getEnforcepremium() {
		return this.enforcepremium;
	}

	public void setEnforcepremium(Double enforcepremium) {
		this.enforcepremium = enforcepremium;
	}

	public Double getEnforcecarshiptax() {
		return this.enforcecarshiptax;
	}

	public void setEnforcecarshiptax(Double enforcecarshiptax) {
		this.enforcecarshiptax = enforcecarshiptax;
	}

	public String getTransType() {
		return this.transType;
	}

	public void setTransType(String transType) {
		this.transType = transType;
	}

	public String getTransStatus() {
		return this.transStatus;
	}

	public void setTransStatus(String transStatus) {
		this.transStatus = transStatus;
	}

	public String getCombineFlag() {
		return this.combineFlag;
	}

	public void setCombineFlag(String combineFlag) {
		this.combineFlag = combineFlag;
	}

	public String getMainproposalno() {
		return this.mainproposalno;
	}

	public void setMainproposalno(String mainproposalno) {
		this.mainproposalno = mainproposalno;
	}


	public PrpCMainsub() {
	}

	public PrpCMainsub(PrpCMainsubId id) {
		this.id = id;
	}

	public PrpCMainsubId getId() {
		return this.id;
	}

	public void setId(PrpCMainsubId id) {
		this.id = id;
	}

}
