package com.sinosoft.efiling.hibernate.entity;

// Generated 2013-3-14 10:03:25 by Hibernate Tools 4.0.0

import java.io.Serializable;

/**
 * PrpdCodeId generated by hbm2java
 */
public class PrpdCodeId implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5065774465623081700L;
	private String codeType;
	private String codeCode;

	public PrpdCodeId() {
	}

	public PrpdCodeId(String codeType, String codeCode) {
		this.codeType = codeType;
		this.codeCode = codeCode;
	}

	public String getCodeType() {
		return this.codeType;
	}

	public void setCodeType(String codeType) {
		this.codeType = codeType;
	}

	public String getCodeCode() {
		return this.codeCode;
	}

	public void setCodeCode(String codeCode) {
		this.codeCode = codeCode;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PrpdCodeId))
			return false;
		PrpdCodeId castOther = (PrpdCodeId) other;

		return ((this.getCodeType() == castOther.getCodeType()) || (this.getCodeType() != null
				&& castOther.getCodeType() != null && this.getCodeType().equals(castOther.getCodeType())))
				&& ((this.getCodeCode() == castOther.getCodeCode()) || (this.getCodeCode() != null
						&& castOther.getCodeCode() != null && this.getCodeCode().equals(castOther.getCodeCode())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCodeType() == null ? 0 : this.getCodeType().hashCode());
		result = 37 * result + (getCodeCode() == null ? 0 : this.getCodeCode().hashCode());
		return result;
	}

}
